//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Views.Shared.TextFile", typeof(TextFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionable tool was created as an exercise in C# and .NET core. It was based on &lt;a href=&quot;https://edabit.com/challenge/uhsik73PY7Y2XftzG&quot; target=&quot;_blank&quot;&gt;this challenge&lt;/a&gt; posted on &lt;a href=&quot;https://edabit.com&quot; target=&quot;_blank&quot;&gt;edabit.com&lt;/a&gt;. .
        /// </summary>
        public static string aboutDescText {
            get {
                return ResourceManager.GetString("aboutDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About PigLatin Translator.
        /// </summary>
        public static string aboutHeaderText {
            get {
                return ResourceManager.GetString("aboutHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to GitHub repo: &lt;a href=&quot;https://github.com/mickaj/piglet&quot; target=&quot;_blank&quot;&gt;github.com/mickaj/piglet&lt;/a&gt;.
        /// </summary>
        public static string aboutVisitGitHubRepo {
            get {
                return ResourceManager.GetString("aboutVisitGitHubRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit my GitHub: &lt;a href=&quot;https://github.com/mickaj&quot; target=&quot;_blank&quot;&gt;github.com/mickaj&lt;/a&gt;.
        /// </summary>
        public static string aboutVisitMyGitHub {
            get {
                return ResourceManager.GetString("aboutVisitMyGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit my blog: &lt;a href=&quot;https://mkajzer.pl&quot; target=&quot;_blank&quot;&gt;mkajzer.pl&lt;/a&gt;.
        /// </summary>
        public static string aboutVisitMyPage {
            get {
                return ResourceManager.GetString("aboutVisitMyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PigLatin Translator.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string cookiesAcceptButton {
            get {
                return ResourceManager.GetString("cookiesAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page uses cookies! To learn more please go to About section or click here -&gt;.
        /// </summary>
        public static string cookiesAlert {
            get {
                return ResourceManager.GetString("cookiesAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string cookiesLearnMore {
            get {
                return ResourceManager.GetString("cookiesLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies policy.
        /// </summary>
        public static string cookiesPolicyHeader {
            get {
                return ResourceManager.GetString("cookiesPolicyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page uses cookies for two purposes: i) anti-forgery token when sending text to translate; ii) track if user dismissed cookie policy alert.&lt;/br&gt;
        ///If you don&apos;t accept this policy please leave this page and delete cookies already created..
        /// </summary>
        public static string cookiesPolicyText {
            get {
                return ResourceManager.GetString("cookiesPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when translating :(.
        /// </summary>
        public static string errorTranslateMessage {
            get {
                return ResourceManager.GetString("errorTranslateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string github {
            get {
                return ResourceManager.GetString("github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to GitHub repository.
        /// </summary>
        public static string github_link_tooltip {
            get {
                return ResourceManager.GetString("github_link_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo GitHub - Link to GitHub repo.
        /// </summary>
        public static string github_logo {
            get {
                return ResourceManager.GetString("github_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car &gt; arcay.
        /// </summary>
        public static string howItWorksExampleConsonant1 {
            get {
                return ResourceManager.GetString("howItWorksExampleConsonant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fallout &gt; alloutfay.
        /// </summary>
        public static string howItWorksExampleConsonant2 {
            get {
                return ResourceManager.GetString("howItWorksExampleConsonant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translator &gt; anslatortray.
        /// </summary>
        public static string howItWorksExampleConsonant3 {
            get {
                return ResourceManager.GetString("howItWorksExampleConsonant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples:.
        /// </summary>
        public static string howItWorksExamplesHeader {
            get {
                return ResourceManager.GetString("howItWorksExamplesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apple &gt; appleyay.
        /// </summary>
        public static string howItWorksExampleVowel1 {
            get {
                return ResourceManager.GetString("howItWorksExampleVowel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit &gt; edityay.
        /// </summary>
        public static string howItWorksExampleVowel2 {
            get {
                return ResourceManager.GetString("howItWorksExampleVowel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elaborate &gt; elaborateyay.
        /// </summary>
        public static string howItWorksExampleVowel3 {
            get {
                return ResourceManager.GetString("howItWorksExampleVowel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works:.
        /// </summary>
        public static string howItWorksHeader {
            get {
                return ResourceManager.GetString("howItWorksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Consonant starting words:&lt;/b&gt; move consonants from the begging of the word to the end and add &quot;ay&quot;.&lt;br&gt;&lt;b&gt;Vowel starting words:&lt;/b&gt; add &quot;yay&quot; at the end of the word..
        /// </summary>
        public static string howItWorksPara {
            get {
                return ResourceManager.GetString("howItWorksPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mickaj.
        /// </summary>
        public static string mickaj {
            get {
                return ResourceManager.GetString("mickaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source text.
        /// </summary>
        public static string sourceTextPlaceholder {
            get {
                return ResourceManager.GetString("sourceTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to target text.
        /// </summary>
        public static string targetTextPlaceholder {
            get {
                return ResourceManager.GetString("targetTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate!.
        /// </summary>
        public static string translateButton {
            get {
                return ResourceManager.GetString("translateButton", resourceCulture);
            }
        }
    }
}
